name: lm_compress
channels:
  - conda-forge
  - defaults
dependencies:
  - appnope=0.1.4
  - asttokens=2.4.1
  - blas=1.0=openblas
  - bottleneck=1.3.7
  - bzip2=1.0.8
  - ca-certificates=2024.3.11
  - comm=0.2.2
  - debugpy=1.6.7
  - decorator=5.1.1
  - exceptiongroup=1.2.0
  - executing=2.0.1
  - importlib-metadata=7.1.0
  - importlib_metadata=7.1.0
  - ipykernel=6.29.3
  - ipython=8.24.0
  - jedi=0.19.1
  - jupyter_client=8.6.2
  - jupyter_core=5.5.0
  - libcxx=14.0.6
  - libffi=3.4.4
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - libopenblas=0.3.21
  - libsodium=1.0.18
  - llvm-openmp=14.0.6
  - matplotlib-inline=0.1.7
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - numexpr=2.8.7
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openssl=3.3.0
  - packaging=24.0
  - pandas=2.2.1
  - parso=0.8.4
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=24.0
  - platformdirs=4.2.2
  - prompt-toolkit=3.0.42
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pygments=2.18.0
  - python=3.10.14
  - python-dateutil=2.9.0post0
  - python-tzdata=2023.3
  - pytz=2024.1
  - pyzmq=25.1.2
  - readline=8.2
  - setuptools=69.5.1
  - six=1.16.0
  - sqlite=3.45.3
  - stack_data=0.6.2
  - tk=8.6.14
  - tornado=6.3.3
  - traitlets=5.14.3
  - typing_extensions=4.11.0
  - tzdata=2024a
  - wcwidth=0.2.13
  - wheel=0.43.0
  - xz=5.4.6
  - zeromq=4.3.5
  - zipp=3.17.0
  - zlib=1.2.13
  - pip:
      - certifi==2024.2.2
      - charset-normalizer==3.3.2
      - contourpy==1.3.0
      - cycler==0.12.1
      - filelock==3.14.0
      - fonttools==4.54.1
      - fsspec==2024.5.0
      - huggingface-hub==0.23.2
      - idna==3.7
      - ipywidgets==8.1.3
      - jinja2==3.1.4
      - joblib==1.4.2
      - jupyterlab-widgets==3.0.11
      - kiwisolver==1.4.7
      - markupsafe==2.1.5
      - matplotlib==3.9.2
      - mpmath==1.3.0
      - networkx==3.3
      - pandas-flavor==0.6.0
      - patsy==0.5.6
      - pillow==10.3.0
      - pingouin==0.5.5
      - pyparsing==3.1.4
      - pyyaml==6.0.1
      - regex==2024.5.15
      - requests==2.32.3
      - safetensors==0.4.3
      - scikit-learn==1.5.0
      - scipy==1.13.1
      - seaborn==0.13.2
      - statsmodels==0.14.3
      - sympy==1.12.1
      - tabulate==0.9.0
      - threadpoolctl==3.5.0
      - tokenizers==0.19.1
      - torch==2.3.1
      - tqdm==4.66.4
      - transformers==4.41.2
      - typing-extensions==4.12.0
      - urllib3==2.2.1
      - widgetsnbextension==4.0.11
      - xarray==2024.9.0
